GET http://localhost:8000/api/customer/get?id=all

###

POST http://localhost:8000/api/admin/login

Content-Type: application/json

{
    "username": "0985805096",
    "password": "matkhaulaso1"
}

###
POST http://localhost:8000/api/customer/login

{
    "phoneNumber": "0964104740",
    "password": "21082001"
}